/**
 * Synthesised audio.
 *
 * Every sound in the museum is generated by Web Audio at runtime. Nothing is
 * downloaded. That is not a purity exercise — it is the right engineering call
 * here for three reasons:
 *
 *   1. A looping set of four recorded footsteps is instantly recognisable as
 *      canned after about twenty steps. Per-step randomisation of pitch, gain
 *      and filter is what makes a walk read as real, and you can only do that
 *      cheaply if you are synthesising in the first place.
 *   2. It costs zero bytes, against a budget where every kilobyte before the
 *      player can move is contested.
 *   3. The surface can change per step from a floor raycast, which a fixed
 *      sample set cannot do without shipping a set per material.
 *
 * A footstep is a short noise burst through a bandpass with a fast decay. The
 * character comes entirely from the filter: marble is bright and short, carpet
 * is dark and long, wood sits in between with a click on top.
 */

export type Surface = 'wood' | 'stone' | 'carpet'

type SurfaceVoice = {
  /** Bandpass centre, Hz. */
  frequency: number
  /** Filter Q. High is a ringing tap, low is a soft thud. */
  q: number
  /** Envelope decay, seconds. */
  decay: number
  gain: number
  /** Optional bright transient layered on top. */
  click?: { frequency: number; gain: number; decay: number }
}

const SURFACES: Record<Surface, SurfaceVoice> = {
  // Sprung maple boards: a body around 400 Hz with a hard tap over it.
  wood: { frequency: 420, q: 3.2, decay: 0.11, gain: 0.5, click: { frequency: 1500, gain: 0.22, decay: 0.035 } },
  // Marble gallery floor: bright, short, ringing.
  stone: { frequency: 2800, q: 7.5, decay: 0.075, gain: 0.42 },
  // Carpet: dark, soft, no transient at all.
  carpet: { frequency: 520, q: 1.1, decay: 0.16, gain: 0.3 },
}

/** ±12% per step. Without this the ear locks onto the repetition immediately. */
const VARIATION = 0.12

type AudioEvents = Pick<EventTarget, 'addEventListener' | 'removeEventListener'>

/** Where the audio graph comes from and where gestures are heard. */
export type AudioEnvironment = {
  readonly createContext: () => AudioContext
  /** Absent outside a browser, where nothing can resume anything. */
  readonly gestures?: AudioEvents
  readonly visibility?: AudioEvents & { readonly visibilityState: DocumentVisibilityState }
}

function browserEnvironment(): AudioEnvironment {
  return {
    createContext: () => new AudioContext(),
    gestures: typeof window === 'undefined' ? undefined : window,
    visibility: typeof document === 'undefined' ? undefined : document,
  }
}

/**
 * Gestures that may resume a context. Permanent listeners rather than `once`:
 * a phone suspends the context again every time the screen locks or a call
 * comes in, and Safari reports 'interrupted' rather than 'suspended'.
 */
const RESUME_GESTURES = ['touchend', 'click', 'pointerup', 'keydown'] as const

export class MuseumAudio {
  private context: AudioContext | null = null
  private master: GainNode | null = null
  private reverb: ConvolverNode | null = null
  private wet: GainNode | null = null
  private noise: AudioBuffer | null = null
  /** Alternating feet, so successive steps are not identical. */
  private foot = 0
  private readonly environment: () => AudioEnvironment
  private unbindResume: (() => void) | null = null

  constructor(environment: () => AudioEnvironment = browserEnvironment) {
    this.environment = environment
  }

  /**
   * Must be called from inside a user gesture — the same click that requests
   * pointer lock. Browsers will not start an AudioContext otherwise, and the
   * classic symptom is audio that works on desktop and is silent on iOS.
   */
  unlock() {
    if (this.context) {
      this.resume()
      return
    }

    const environment = this.environment()
    const context = environment.createContext()
    this.context = context
    this.bindResume(environment, context)

    this.master = context.createGain()
    this.master.gain.value = 0.7
    this.master.connect(context.destination)

    // A synthesised impulse response: exponentially decaying stereo noise.
    // A real gallery is 1.5-2 s of reverb, and generating it costs nothing
    // where shipping an IR file would cost a couple of hundred kilobytes.
    this.reverb = context.createConvolver()
    this.reverb.buffer = this.makeImpulse(1.9, 2.6)
    this.wet = context.createGain()
    this.wet.gain.value = 0.28
    this.reverb.connect(this.wet)
    this.wet.connect(this.master)

    // One second of white noise, reused by every footstep.
    const length = context.sampleRate
    const noise = context.createBuffer(1, length, context.sampleRate)
    const data = noise.getChannelData(0)
    for (let index = 0; index < length; index += 1) data[index] = Math.random() * 2 - 1
    this.noise = noise
  }

  /**
   * Restarts a context the platform has paused.
   *
   * The title screen's click unlocks audio once, and there is no way back to
   * the title: without this, the first screen lock on a phone silenced the
   * latch, the radio and every footstep for the rest of the visit. After the
   * first unlock iOS no longer insists on a gesture, so a resume on returning
   * to the page often works alone; when it does not, the next tap does.
   */
  resume() {
    const context = this.context
    const state = context?.state as string | undefined
    if (!context || state === 'running' || state === 'closed') return
    void context.resume().catch(() => {
      // Refused without a gesture; the next gesture listener tries again.
    })
  }

  private bindResume(environment: AudioEnvironment, context: AudioContext) {
    const resume = () => this.resume()
    const visible = () => environment.visibility?.visibilityState !== 'hidden'
    const resumeWhenVisible = () => {
      if (visible()) this.resume()
    }
    const options = { capture: true, passive: true } as const
    for (const type of RESUME_GESTURES) environment.gestures?.addEventListener(type, resume, options)
    environment.visibility?.addEventListener('visibilitychange', resumeWhenVisible)
    // An interruption while the page stays visible (a notification sound, an
    // alarm) ends without any page event at all; the state change is the cue.
    context.onstatechange = resumeWhenVisible

    this.unbindResume = () => {
      for (const type of RESUME_GESTURES) {
        environment.gestures?.removeEventListener(type, resume, options)
      }
      environment.visibility?.removeEventListener('visibilitychange', resumeWhenVisible)
      context.onstatechange = null
    }
  }

  /**
   * The context, only while it is actually running. Scheduling sounds on a
   * suspended or interrupted context queues them to burst out together the
   * moment it resumes.
   */
  private live(): AudioContext | null {
    const context = this.context
    return context && context.state === 'running' ? context : null
  }

  private makeImpulse(seconds: number, falloff: number): AudioBuffer {
    const context = this.context as AudioContext
    const length = Math.floor(context.sampleRate * seconds)
    const impulse = context.createBuffer(2, length, context.sampleRate)

    for (let channel = 0; channel < 2; channel += 1) {
      const data = impulse.getChannelData(channel)
      for (let index = 0; index < length; index += 1) {
        const progress = index / length
        data[index] = (Math.random() * 2 - 1) * Math.pow(1 - progress, falloff)
      }
    }

    return impulse
  }

  /** One footstep. `intensity` is 0..1, from the player's speed. */
  footstep(surface: Surface = 'wood', intensity = 1) {
    const context = this.live()
    if (!context || !this.noise || !this.master || !this.reverb) return

    const voice = SURFACES[surface] ?? SURFACES.wood
    const now = context.currentTime
    // Alternating feet get a consistent offset on top of the random jitter, so
    // the gait has a left-right character rather than sounding like one foot
    // hopping.
    this.foot = 1 - this.foot
    const footBias = this.foot === 0 ? 1 : 0.94
    const jitter = 1 + (Math.random() * 2 - 1) * VARIATION

    const play = (spec: { frequency: number; q?: number; gain: number; decay: number }) => {
      const source = context.createBufferSource()
      source.buffer = this.noise as AudioBuffer
      source.loop = true

      const filter = context.createBiquadFilter()
      filter.type = 'bandpass'
      filter.frequency.value = spec.frequency * jitter * footBias
      filter.Q.value = spec.q ?? 4

      const envelope = context.createGain()
      const peak = spec.gain * intensity * (0.88 + Math.random() * 0.24)
      // A footstep has essentially no attack; the shape is all in the decay.
      envelope.gain.setValueAtTime(0.0001, now)
      envelope.gain.exponentialRampToValueAtTime(Math.max(peak, 0.0002), now + 0.004)
      envelope.gain.exponentialRampToValueAtTime(0.0001, now + spec.decay)

      source.connect(filter)
      filter.connect(envelope)
      envelope.connect(this.master as GainNode)
      envelope.connect(this.reverb as ConvolverNode)

      source.start(now)
      source.stop(now + spec.decay + 0.02)
    }

    play({ frequency: voice.frequency, q: voice.q, gain: voice.gain, decay: voice.decay })
    if (voice.click) {
      play({ frequency: voice.click.frequency, q: 2.5, gain: voice.click.gain, decay: voice.click.decay })
    }
  }

  /** A soft confirmation, used when something enters the catalogue. */
  chime() {
    const context = this.live()
    if (!context || !this.master) return

    const now = context.currentTime
    // A fifth, quiet and short. Anything longer becomes a reward jingle, which
    // is the wrong register entirely for a museum.
    for (const [index, frequency] of [523.25, 783.99].entries()) {
      const oscillator = context.createOscillator()
      oscillator.type = 'sine'
      oscillator.frequency.value = frequency

      const envelope = context.createGain()
      const start = now + index * 0.07
      envelope.gain.setValueAtTime(0.0001, start)
      envelope.gain.exponentialRampToValueAtTime(0.09, start + 0.02)
      envelope.gain.exponentialRampToValueAtTime(0.0001, start + 0.9)

      oscillator.connect(envelope)
      envelope.connect(this.master)
      if (this.reverb) envelope.connect(this.reverb)
      oscillator.start(start)
      oscillator.stop(start + 0.95)
    }
  }

  /** Short mortice-latch click followed by a restrained timber hinge creak. */
  doorOpen(duration = 0.8) {
    const context = this.live()
    if (!context || !this.master || !this.noise) return

    const now = context.currentTime

    const latch = context.createOscillator()
    latch.type = 'triangle'
    latch.frequency.setValueAtTime(980, now)
    latch.frequency.exponentialRampToValueAtTime(420, now + 0.055)
    const latchGain = context.createGain()
    latchGain.gain.setValueAtTime(0.0001, now)
    latchGain.gain.exponentialRampToValueAtTime(0.12, now + 0.004)
    latchGain.gain.exponentialRampToValueAtTime(0.0001, now + 0.07)
    latch.connect(latchGain)
    latchGain.connect(this.master)
    if (this.reverb) latchGain.connect(this.reverb)
    latch.start(now)
    latch.stop(now + 0.08)

    const hinge = context.createBufferSource()
    hinge.buffer = this.noise
    hinge.loop = true
    const filter = context.createBiquadFilter()
    filter.type = 'bandpass'
    filter.frequency.setValueAtTime(260, now + 0.05)
    filter.frequency.exponentialRampToValueAtTime(115, now + duration)
    filter.Q.value = 7
    const hingeGain = context.createGain()
    hingeGain.gain.setValueAtTime(0.0001, now + 0.04)
    hingeGain.gain.exponentialRampToValueAtTime(0.045, now + 0.12)
    hingeGain.gain.exponentialRampToValueAtTime(0.0001, now + duration)
    hinge.connect(filter)
    filter.connect(hingeGain)
    hingeGain.connect(this.master)
    if (this.reverb) hingeGain.connect(this.reverb)
    hinge.start(now + 0.04)
    hinge.stop(now + duration + 0.02)
  }

  /** A short square-wave buzz: an electric lock refusing a press without power. */
  lockDenied() {
    const context = this.live()
    if (!context || !this.master) return

    const now = context.currentTime
    for (const offset of [0, 0.11]) {
      const buzz = context.createOscillator()
      buzz.type = 'square'
      buzz.frequency.value = 148
      const filter = context.createBiquadFilter()
      filter.type = 'lowpass'
      filter.frequency.value = 900
      const gain = context.createGain()
      gain.gain.setValueAtTime(0.0001, now + offset)
      gain.gain.exponentialRampToValueAtTime(0.05, now + offset + 0.008)
      gain.gain.exponentialRampToValueAtTime(0.0001, now + offset + 0.085)
      buzz.connect(filter)
      filter.connect(gain)
      gain.connect(this.master)
      buzz.start(now + offset)
      buzz.stop(now + offset + 0.1)
    }
  }

  /**
   * The electric strike letting go: a solenoid thunk and a bright tick.
   * `gain` scales it with the listener's distance from the door.
   */
  lockRelease(gain = 1) {
    const context = this.live()
    if (!context || !this.master || !this.noise) return

    const now = context.currentTime
    const thunk = context.createOscillator()
    thunk.type = 'sine'
    thunk.frequency.setValueAtTime(190, now)
    thunk.frequency.exponentialRampToValueAtTime(70, now + 0.09)
    const thunkGain = context.createGain()
    thunkGain.gain.setValueAtTime(0.0001, now)
    thunkGain.gain.exponentialRampToValueAtTime(0.16 * gain, now + 0.005)
    thunkGain.gain.exponentialRampToValueAtTime(0.0001, now + 0.12)
    thunk.connect(thunkGain)
    thunkGain.connect(this.master)
    if (this.reverb) thunkGain.connect(this.reverb)
    thunk.start(now)
    thunk.stop(now + 0.13)

    const tick = context.createBufferSource()
    tick.buffer = this.noise
    const filter = context.createBiquadFilter()
    filter.type = 'bandpass'
    filter.frequency.value = 3200
    filter.Q.value = 6
    const tickGain = context.createGain()
    tickGain.gain.setValueAtTime(0.0001, now + 0.02)
    tickGain.gain.exponentialRampToValueAtTime(0.12 * gain, now + 0.024)
    tickGain.gain.exponentialRampToValueAtTime(0.0001, now + 0.06)
    tick.connect(filter)
    filter.connect(tickGain)
    tickGain.connect(this.master)
    tick.start(now + 0.02)
    tick.stop(now + 0.07)
  }

  /** The radio opening: a burst of band-limited static and a two-tone beep. */
  radioSquelch() {
    const context = this.live()
    if (!context || !this.master || !this.noise) return

    const now = context.currentTime
    const hiss = context.createBufferSource()
    hiss.buffer = this.noise
    hiss.loop = true
    const band = context.createBiquadFilter()
    band.type = 'bandpass'
    band.frequency.value = 1800
    band.Q.value = 0.9
    const hissGain = context.createGain()
    hissGain.gain.setValueAtTime(0.0001, now)
    hissGain.gain.exponentialRampToValueAtTime(0.07, now + 0.02)
    hissGain.gain.exponentialRampToValueAtTime(0.0001, now + 0.32)
    hiss.connect(band)
    band.connect(hissGain)
    hissGain.connect(this.master)
    hiss.start(now)
    hiss.stop(now + 0.34)

    for (const [index, frequency] of [1320, 990].entries()) {
      const beep = context.createOscillator()
      beep.type = 'sine'
      beep.frequency.value = frequency
      const beepGain = context.createGain()
      const start = now + 0.08 + index * 0.09
      beepGain.gain.setValueAtTime(0.0001, start)
      beepGain.gain.exponentialRampToValueAtTime(0.045, start + 0.01)
      beepGain.gain.exponentialRampToValueAtTime(0.0001, start + 0.08)
      beep.connect(beepGain)
      beepGain.connect(this.master)
      beep.start(start)
      beep.stop(start + 0.09)
    }
  }

  /** A faint crackle between two lines of the same transmission. */
  radioCrackle() {
    const context = this.live()
    if (!context || !this.master || !this.noise) return

    const now = context.currentTime
    const crackle = context.createBufferSource()
    crackle.buffer = this.noise
    const filter = context.createBiquadFilter()
    filter.type = 'highpass'
    filter.frequency.value = 2400
    const gain = context.createGain()
    gain.gain.setValueAtTime(0.0001, now)
    gain.gain.exponentialRampToValueAtTime(0.03, now + 0.01)
    gain.gain.exponentialRampToValueAtTime(0.0001, now + 0.12)
    crackle.connect(filter)
    filter.connect(gain)
    gain.connect(this.master)
    crackle.start(now)
    crackle.stop(now + 0.13)
  }

  setVolume(value: number) {
    if (this.master) this.master.gain.value = Math.max(0, Math.min(1, value))
  }

  dispose() {
    this.unbindResume?.()
    this.unbindResume = null
    void this.context?.close()
    this.context = null
  }
}

/** One instance for the app. Audio graphs are not something to have two of. */
export const museumAudio = new MuseumAudio()
