/**
 * Synthesised audio.
 *
 * Every sound in the museum is generated by Web Audio at runtime. Nothing is
 * downloaded. That is not a purity exercise — it is the right engineering call
 * here for three reasons:
 *
 *   1. A looping set of four recorded footsteps is instantly recognisable as
 *      canned after about twenty steps. Per-step randomisation of pitch, gain
 *      and filter is what makes a walk read as real, and you can only do that
 *      cheaply if you are synthesising in the first place.
 *   2. It costs zero bytes, against a budget where every kilobyte before the
 *      player can move is contested.
 *   3. The surface can change per step from a floor raycast, which a fixed
 *      sample set cannot do without shipping a set per material.
 *
 * A footstep is a short noise burst through a bandpass with a fast decay. The
 * character comes entirely from the filter: marble is bright and short, carpet
 * is dark and long, wood sits in between with a click on top.
 */

export type Surface = 'wood' | 'stone' | 'carpet'

type SurfaceVoice = {
  /** Bandpass centre, Hz. */
  frequency: number
  /** Filter Q. High is a ringing tap, low is a soft thud. */
  q: number
  /** Envelope decay, seconds. */
  decay: number
  gain: number
  /** Optional bright transient layered on top. */
  click?: { frequency: number; gain: number; decay: number }
}

const SURFACES: Record<Surface, SurfaceVoice> = {
  // Sprung maple boards: a body around 400 Hz with a hard tap over it.
  wood: { frequency: 420, q: 3.2, decay: 0.11, gain: 0.5, click: { frequency: 1500, gain: 0.22, decay: 0.035 } },
  // Marble gallery floor: bright, short, ringing.
  stone: { frequency: 2800, q: 7.5, decay: 0.075, gain: 0.42 },
  // Carpet: dark, soft, no transient at all.
  carpet: { frequency: 520, q: 1.1, decay: 0.16, gain: 0.3 },
}

/** ±12% per step. Without this the ear locks onto the repetition immediately. */
const VARIATION = 0.12

export class MuseumAudio {
  private context: AudioContext | null = null
  private master: GainNode | null = null
  private reverb: ConvolverNode | null = null
  private wet: GainNode | null = null
  private noise: AudioBuffer | null = null
  /** Alternating feet, so successive steps are not identical. */
  private foot = 0

  /**
   * Must be called from inside a user gesture — the same click that requests
   * pointer lock. Browsers will not start an AudioContext otherwise, and the
   * classic symptom is audio that works on desktop and is silent on iOS.
   */
  unlock() {
    if (this.context) {
      if (this.context.state === 'suspended') void this.context.resume()
      return
    }

    const context = new AudioContext()
    this.context = context

    this.master = context.createGain()
    this.master.gain.value = 0.7
    this.master.connect(context.destination)

    // A synthesised impulse response: exponentially decaying stereo noise.
    // A real gallery is 1.5-2 s of reverb, and generating it costs nothing
    // where shipping an IR file would cost a couple of hundred kilobytes.
    this.reverb = context.createConvolver()
    this.reverb.buffer = this.makeImpulse(1.9, 2.6)
    this.wet = context.createGain()
    this.wet.gain.value = 0.28
    this.reverb.connect(this.wet)
    this.wet.connect(this.master)

    // One second of white noise, reused by every footstep.
    const length = context.sampleRate
    const noise = context.createBuffer(1, length, context.sampleRate)
    const data = noise.getChannelData(0)
    for (let index = 0; index < length; index += 1) data[index] = Math.random() * 2 - 1
    this.noise = noise
  }

  private makeImpulse(seconds: number, falloff: number): AudioBuffer {
    const context = this.context as AudioContext
    const length = Math.floor(context.sampleRate * seconds)
    const impulse = context.createBuffer(2, length, context.sampleRate)

    for (let channel = 0; channel < 2; channel += 1) {
      const data = impulse.getChannelData(channel)
      for (let index = 0; index < length; index += 1) {
        const progress = index / length
        data[index] = (Math.random() * 2 - 1) * Math.pow(1 - progress, falloff)
      }
    }

    return impulse
  }

  /** One footstep. `intensity` is 0..1, from the player's speed. */
  footstep(surface: Surface = 'wood', intensity = 1) {
    const context = this.context
    if (!context || !this.noise || !this.master || !this.reverb) return
    if (context.state === 'suspended') return

    const voice = SURFACES[surface] ?? SURFACES.wood
    const now = context.currentTime
    // Alternating feet get a consistent offset on top of the random jitter, so
    // the gait has a left-right character rather than sounding like one foot
    // hopping.
    this.foot = 1 - this.foot
    const footBias = this.foot === 0 ? 1 : 0.94
    const jitter = 1 + (Math.random() * 2 - 1) * VARIATION

    const play = (spec: { frequency: number; q?: number; gain: number; decay: number }) => {
      const source = context.createBufferSource()
      source.buffer = this.noise as AudioBuffer
      source.loop = true

      const filter = context.createBiquadFilter()
      filter.type = 'bandpass'
      filter.frequency.value = spec.frequency * jitter * footBias
      filter.Q.value = spec.q ?? 4

      const envelope = context.createGain()
      const peak = spec.gain * intensity * (0.88 + Math.random() * 0.24)
      // A footstep has essentially no attack; the shape is all in the decay.
      envelope.gain.setValueAtTime(0.0001, now)
      envelope.gain.exponentialRampToValueAtTime(Math.max(peak, 0.0002), now + 0.004)
      envelope.gain.exponentialRampToValueAtTime(0.0001, now + spec.decay)

      source.connect(filter)
      filter.connect(envelope)
      envelope.connect(this.master as GainNode)
      envelope.connect(this.reverb as ConvolverNode)

      source.start(now)
      source.stop(now + spec.decay + 0.02)
    }

    play({ frequency: voice.frequency, q: voice.q, gain: voice.gain, decay: voice.decay })
    if (voice.click) {
      play({ frequency: voice.click.frequency, q: 2.5, gain: voice.click.gain, decay: voice.click.decay })
    }
  }

  /** A soft confirmation, used when something enters the catalogue. */
  chime() {
    const context = this.context
    if (!context || !this.master) return

    const now = context.currentTime
    // A fifth, quiet and short. Anything longer becomes a reward jingle, which
    // is the wrong register entirely for a museum.
    for (const [index, frequency] of [523.25, 783.99].entries()) {
      const oscillator = context.createOscillator()
      oscillator.type = 'sine'
      oscillator.frequency.value = frequency

      const envelope = context.createGain()
      const start = now + index * 0.07
      envelope.gain.setValueAtTime(0.0001, start)
      envelope.gain.exponentialRampToValueAtTime(0.09, start + 0.02)
      envelope.gain.exponentialRampToValueAtTime(0.0001, start + 0.9)

      oscillator.connect(envelope)
      envelope.connect(this.master)
      if (this.reverb) envelope.connect(this.reverb)
      oscillator.start(start)
      oscillator.stop(start + 0.95)
    }
  }

  setVolume(value: number) {
    if (this.master) this.master.gain.value = Math.max(0, Math.min(1, value))
  }

  dispose() {
    void this.context?.close()
    this.context = null
  }
}

/** One instance for the app. Audio graphs are not something to have two of. */
export const museumAudio = new MuseumAudio()
